name: Post Office
id: postoffice
key: postoffice
author_link: http://www.movabletype.org/
author_name: Six Apart Ltd.
description: Reads from e-mail and posts to MT.
version: 2.0
plugin_link: https://github.com/tkeating/mt-plugin-post-office

applications:
    cms:
        init: >>
            sub {
                my $c = MT->component('postoffice');
                $c->{config_template} = MT->handler_to_coderef('$postoffice::PostOffice::CMS::config_template');
            }

settings:
    email_address:
        Default: ''
    email_username:
        Default: ''
    email_password:
        Default: ''
    email_host:
        Default: ''
    email_transport:
        Default: pop3
    imap_folder:
        Default: INBOX
    use_ssl:
        Default: 0
    allow_mt_authors:
        Default: 1
    require_api_key:
        Default: 1
    default_author:
        Default: 1
    allowed_emails:
        Default: email@yourdomain.com
    post_assets:
        Default: 0
    post_status:
        Default: 2
    max_image_width:
        Default: 600

callbacks:
    MT::App::CMS::template_source.edit_entry: $postoffice::PostOffice::CMS::edit_entry_src

postoffice_transports:
    imap:
        label: IMAP
        class: PostOffice::Transport::IMAP
    pop3:
        label: POP3
        class: PostOffice::Transport::POP3

tasks:
    PostOfficeDelivery:
        frequency: 1
        label: PostOffice Delivery
        code: >
            sub {
                require PostOffice;
                return PostOffice->deliver;
            }
